name: aloha-pizza-prod

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - aloha-pizza

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - aloha-pizza
    ports:
      - 5000:5000
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - aloha-pizza
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  mongo_data:
networks:
  aloha-pizza:
    driver: bridge
